### ISSUE TITLE
Difference Between ChimpNNoIndex and ChimpN?

### ISSUE THREAD

**Issue by ZhenChen008** [panagiotisl/chimp#3]
Hi, thanks for your code ! I would like to ask what  does **ChimpNNoIndex** mean ?  
It's compression ratio is higher, but what is the main difference between it and ChimpN?

**Comment by panagiotisl** [comment]
if my memory serves me right ChimpNNoIndex considers the use of the best value out of the last N encountered, whereas ChimpN uses a ring buffer to quickly select the most recent value with an identical trailing part out of the last N values encountered. This means that ChimpNNoIndex has a slightly better compression ratio (negligible) at the cost of XORing with all N values instead of a single one (which translates to significant computation overhead).

**Comment by ZhenChen008** [comment]
Okay, I understand. Thanks for your reply!
